server:
  port: 8085
spring:
  application:
    name: searchservice
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  rabbitmq:
    host: 192.168.169.133
    virtual-host: /
    username: itcast
    password: 123321
    port: 5672