server:
  port: 8081
spring:
  application:
    name: itemservice
  datasource:
    url: jdbc:mysql://localhost:3306/weifuwu?useSSL=false
    username: root
    password: jinda111
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848
  rabbitmq:
    host: 192.168.169.133
    port: 5672
    virtual-host: /
    username: itcast
    password: 123321
mybatis-plus:
  type-aliases-package: com.hmall.item.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
