server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weifuwu?useSSL=false
    username: root
    password: jinda111
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userservice
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  type-aliases-package: com.hmall.user.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto